# Generated by Django 5.0 on 2026-09-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report',
            field=models.BooleanField(default=False),
        ),
    ]
